inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

#以下にはrubocopで検証したくないフォルダを指定する
AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'node_modules/******/****/***/**/*'
