default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['PGHOST'] || 'db' %>
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: tabisora_development


test:
  <<: *default
  database: tabisora_test


production:
  <<: *default
  database: tabisora_production
  username: tabisora
  password: <%= ENV['TABISORA_DATABASE_PASSWORD'] %>
